"""
Generates a custom PixelRoot32 bitmap Font from Press Start 2P (Google
Fonts, SIL OFL 1.1 — see tools/fonts/OFL.txt), the canonical "8-bit
arcade" pixel font. Replaces the engine's built-in default font
(Font5x7 — a plain, tiny debug-looking bitmap font) for the menu's plain
text (entries, "coming soon" tag, control hint), which was reported live
as looking bad on its own.

Font format (pixelroot32::graphics::Font / Sprite, see
include/graphics/Font.h and Renderer.h — NOT the same as the 4bpp indexed
Sprite4bpp the other *_sprites.h files export): a fixed-width bitmap font
where each glyph is a monochrome (1bpp) Sprite — an array of uint16_t
rows, bit 0 = leftmost pixel, only the low `width` bits of each row used.
drawText() draws each glyph with drawSprite(glyph, x, y, color, false),
i.e. a single named Color tints the WHOLE glyph — no per-glyph palette,
so there's no palette-budget concern here at all, unlike every other
sprite export script in this project.

Press Start 2P is exactly monospace at integer point sizes (confirmed by
measuring: every character's advance width equals the point size, and the
full 32-90 range's tight bounding box height also equals the point size),
which is exactly what a fixed-width bitmap Font needs — no per-glyph
cropping/alignment logic required, just rasterize each character into a
size x size cell at a fixed origin.

Generates TWO sizes: a larger one (kFontLarge, 12px) for menu entry
labels, a smaller one (kFontSmall, 8px) for secondary text (the "coming
soon" tag, the bottom control hint) that needs to fit more characters in
less width.
"""
import os
from PIL import Image, ImageDraw, ImageFont

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
FONT_PATH = os.path.join(SCRIPT_DIR, "fonts", "PressStart2P-Regular.ttf")
HEADER_PATH = os.path.join(SCRIPT_DIR, "..", "src", "menu_pr32_font.h")

FIRST_CHAR = 32   # ' '
LAST_CHAR = 90    # 'Z' -- covers space, digits, common punctuation, uppercase
ALPHA_THRESHOLD = 128


def rasterize_glyph(font, size, code):
    """Renders one character into a size x size 1bpp bitmap (list of int
    row-bitmasks), using the font's own fixed origin so every glyph lines
    up on the same baseline (no per-glyph bbox cropping, which would
    misalign narrow characters like '.' or ':').

    Bit order: Sprite.h's own doc comment says "bit 0 = leftmost pixel",
    but the REAL drawSprite() implementation (Renderer.cpp) does the
    opposite — its own comment there is explicit: "bit (width-1) = leftmost
    pixel, bit 0 = rightmost pixel". Packing bit0=leftmost (trusting the
    header doc) mirrored every glyph — reported live as scrambled/reversed
    -looking menu text. Fixed by packing MSB-first to match the actual
    renderer, not the stale header comment.
    """
    img = Image.new("L", (size, size), 0)
    draw = ImageDraw.Draw(img)
    draw.text((0, 0), chr(code), font=font, fill=255)
    px = img.load()
    rows = []
    for y in range(size):
        bits = 0
        for x in range(size):
            if px[x, y] >= ALPHA_THRESHOLD:
                bits |= (1 << (size - 1 - x))
        rows.append(bits)
    return rows


def emit_font(f, name, size):
    font = ImageFont.truetype(FONT_PATH, size)
    f.write(f"// {name}: {size}x{size} Press Start 2P glyphs, chars {FIRST_CHAR}..{LAST_CHAR}\n")
    row_names = []
    for code in range(FIRST_CHAR, LAST_CHAR + 1):
        rows = rasterize_glyph(font, size, code)
        row_name = f"{name}_GLYPH_{code}_ROWS"
        row_names.append(row_name)
        hex_rows = ", ".join(f"0x{r:04X}" for r in rows)
        f.write(f"static const uint16_t {row_name}[] = {{ {hex_rows} }};\n")
    f.write(f"static const pixelroot32::graphics::Sprite {name}_GLYPHS[] = {{\n")
    for row_name in row_names:
        f.write(f"    {{ {row_name}, {size}, {size} }},\n")
    f.write("};\n")
    f.write(
        f"static const pixelroot32::graphics::Font {name} = "
        f"{{ {name}_GLYPHS, {FIRST_CHAR}, {LAST_CHAR}, {size}, {size}, 1, {size + 2} }};\n\n"
    )


with open(HEADER_PATH, "w") as f:
    f.write("// AUTO-GENERATED by tools/make_menu_pr32_font.py — do not hand-edit.\n")
    f.write("// Press Start 2P (Google Fonts, SIL OFL 1.1, see tools/fonts/OFL.txt),\n")
    f.write("// rasterized into PixelRoot32's 1bpp bitmap Font format.\n")
    f.write("#pragma once\n")
    f.write("#include <cstdint>\n")
    f.write("#include <graphics/Font.h>\n")
    f.write("#include <graphics/Renderer.h>\n\n")
    f.write("namespace menu_pr32_font {\n\n")
    emit_font(f, "FONT_LARGE", 12)
    emit_font(f, "FONT_SMALL", 8)
    f.write("} // namespace menu_pr32_font\n")

print("Generated menu_pr32_font.h (FONT_LARGE=12px, FONT_SMALL=8px)")
