"""
Draws an ORIGINAL small paddle-shaped "ship" for Arkanoid's title screen,
entirely from scratch with PIL primitives — not cropped or traced from
any reference project or the real arcade. A horizontal rounded-capsule
silhouette (nose caps on each end, a cockpit canopy in the middle) whose
main body cycles through a full rainbow hue rotation across 8 frames for
a clean pulsing-color loop animation, distinct from the in-game Vaus
paddle's fixed chrome-and-orange coloring.

Same pack pipeline as every other make_*_pr32_*.py script in this
project.
"""
import colorsys
import os
from PIL import Image, ImageDraw

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
OUT_DIR = os.path.join(SCRIPT_DIR, "sprite_previews", "arkanoid_pr32")
HEADER_PATH = os.path.join(SCRIPT_DIR, "..", "src", "arkanoid_pr32_ship.h")
os.makedirs(OUT_DIR, exist_ok=True)

W, H = 32, 12
NUM_FRAMES = 8


def hue_color(t):
    """t in [0,1) -> a saturated RGB tuple, evenly spaced around the wheel."""
    r, g, b = colorsys.hsv_to_rgb(t, 0.9, 1.0)
    return (int(r * 255), int(g * 255), int(b * 255), 255)


def draw_ship(frame):
    img = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    body_color = hue_color(frame / NUM_FRAMES)

    # Rounded horizontal capsule body — paddle-shaped, per explicit spec.
    d.rounded_rectangle([2, 2, W - 3, H - 3], radius=4, fill=body_color)

    # Dark outline so the capsule reads clearly against any background.
    d.rounded_rectangle([2, 2, W - 3, H - 3], radius=4, outline=(0, 0, 0, 255), width=1)

    # Fixed chrome-white gloss stripe through the vertical middle (stays
    # constant across frames — only the body hue cycles).
    d.rectangle([4, H // 2 - 1, W - 5, H // 2], fill=(255, 255, 255, 255))

    # Cockpit canopy in the center, fixed cyan (a constant "core" accent
    # against the cycling hull color, like the reference's own paddle
    # canopy idea, but a distinct shape/position here).
    cx = W / 2
    d.ellipse([cx - 3, 1, cx + 3, H - 2], fill=(40, 220, 255, 255))
    d.ellipse([cx - 1.5, 2, cx + 1.5, 5], fill=(220, 250, 255, 255))

    # Small dark end caps (nose tips) so the silhouette doesn't read as a
    # plain bar — a rounded-off paddle "ship" rather than a rectangle.
    d.ellipse([0, 3, 5, H - 4], fill=(30, 30, 30, 255))
    d.ellipse([W - 6, 3, W - 1, H - 4], fill=(30, 30, 30, 255))

    return img


frames = [draw_ship(i) for i in range(NUM_FRAMES)]
for i, f in enumerate(frames):
    f.save(os.path.join(OUT_DIR, f"ship_frame_{i}.png"))


def to_rgb565(r, g, b):
    return ((b & 0xF8) << 8) | ((g & 0xFC) << 3) | (r >> 3)


ALPHA_THRESHOLD = 128
palette_rgb = [(0, 0, 0)]
color_to_index = {(0, 0, 0): 0}


def palette_index_for(rgb):
    if rgb not in color_to_index:
        if len(palette_rgb) >= 16:
            raise ValueError(f"Palette overflow: {rgb} would be the 17th color")
        color_to_index[rgb] = len(palette_rgb)
        palette_rgb.append(rgb)
    return color_to_index[rgb]


def pack_4bpp(img):
    w, h = img.size
    px = img.load()
    row_stride = (w * 4 + 7) // 8
    data = bytearray(row_stride * h)
    for y in range(h):
        for x in range(w):
            r, g, b, a = px[x, y]
            idx = 0 if a < ALPHA_THRESHOLD else palette_index_for((r, g, b))
            byte_i = y * row_stride + (x >> 1)
            if x & 1:
                data[byte_i] |= (idx & 0x0F) << 4
            else:
                data[byte_i] |= (idx & 0x0F)
    return data


frame_data = [pack_4bpp(f) for f in frames]

while len(palette_rgb) < 16:
    palette_rgb.append((0, 0, 0))

header_lines = []
header_lines.append("// AUTO-GENERATED by tools/make_arkanoid_pr32_ship.py — do not hand-edit.")
header_lines.append("// An ORIGINAL paddle-shaped ship design (not from any reference),")
header_lines.append("// 8-frame rainbow hue-cycle animation.")
header_lines.append("#pragma once")
header_lines.append("#include <cstdint>")
header_lines.append("#include <graphics/Renderer.h>")
header_lines.append("")
header_lines.append("namespace arkanoid_pr32_ship {")
header_lines.append("")
for i, data in enumerate(frame_data):
    hex_bytes = ", ".join(f"0x{b:02X}" for b in data)
    header_lines.append(f"static const uint8_t SHIP_FRAME_{i}_DATA[] = {{ {hex_bytes} }};")
header_lines.append("")
header_lines.append("static const uint16_t PALETTE_RGB565[16] = {")
header_lines.append("    " + ", ".join(f"0x{to_rgb565(r, g, b):04X}" for (r, g, b) in palette_rgb))
header_lines.append("};")
header_lines.append("")
header_lines.append("static const pixelroot32::graphics::Color PALETTE_COLORS[16] = {")
header_lines.append("    " + ", ".join(f"static_cast<pixelroot32::graphics::Color>({i})" for i in range(16)))
header_lines.append("};")
header_lines.append("")
for i in range(NUM_FRAMES):
    header_lines.append(
        f"static const pixelroot32::graphics::Sprite4bpp SHIP_FRAME_{i} = "
        f"{{ SHIP_FRAME_{i}_DATA, PALETTE_COLORS, {W}, {H}, 16 }};"
    )
header_lines.append("")
names = ", ".join(f"&SHIP_FRAME_{i}" for i in range(NUM_FRAMES))
header_lines.append(
    f"static const pixelroot32::graphics::Sprite4bpp* const SHIP_FRAMES[{NUM_FRAMES}] = {{ {names} }};"
)
header_lines.append(f"static constexpr int SHIP_NUM_FRAMES = {NUM_FRAMES};")
header_lines.append("")
header_lines.append("} // namespace arkanoid_pr32_ship")

with open(HEADER_PATH, "w") as f:
    f.write("\n".join(header_lines) + "\n")

print(f"Generated {W}x{H} ship, {NUM_FRAMES} frames, {len(color_to_index)} colors used (of 15 available)")
