"""
Exports Arkanoid's Round 1 background (floor tile + baked-in wall
border) AND the Vaus paddle as packed 4bpp indexed bitmaps for
PixelRoot32, both cropped from a SECOND reference project —
dawid-wolinski/arkanoid-game (cloned to /tmp/ark_ref2 this session).

Background: assets/textures/Backgrounds.png's first (top-left) tile is
Round 1's exact blue diamond-scale floor + gray riveted wall border —
the FIRST reference (wkeeling/arkanoid) turned out to only fill a flat
solid color at runtime (arkanoid/rounds/base.py), so this is the real
asset. The tile is resized to the FULL (SCREEN_W x SCREEN_H-kTopWallY)
area needed — including the wall graphics baked into its edges, so the
walls extend the full height too, matching the reference exactly rather
than an earlier pass here that stopped short and patched the remainder
with a flat-color rect. Sprite4bpp's width/height fields are uint8_t
(max 255 — see Renderer.h), so the resized image is split into two
vertical slices sharing ONE quantized palette (drawn stacked with two
back-to-back drawSprite() calls) — this reproduces the resized pattern
EXACTLY at the seam (it's literally one image cut in half), not an
approximation.

Paddle: the reference's own paddle.cpp points at
assets/textures/Palettes.png with sf::IntRect(208, 0, 32, 8) (right x,
wrong y — that rect is blank; the same x=208 turned out to be right once
the correct y was found). The sheet packs many paddle frames edge to
edge with only a 1px black divider between them (not a real gap), so an
early crop attempt here (28, 32, 68, 40) landed mid-sprite and picked up
slivers of the NEXT paddles on both sides — visible live as "showing
ends of the paddles next to it." Fixed by finding one fully ISOLATED
instance (surrounded by real empty space, not packed against neighbors)
via a row-by-row non-black bounding-box scan: (208, 34, 252, 41), 44x7
native — confirmed clean by eye before committing to these coordinates.

Same crop -> resize -> quantize -> pack_4bpp -> export pipeline as every
other make_*_pr32_sprites.py script (see make_galaga_pr32_sprites.py's
docstring for the packed-format rationale and the real-panel R/B swap
this project's hardware needs — applied identically here via the same
to_rgb565() bit layout).
"""
import os
from PIL import Image

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
BG_PNG = "/tmp/ark_ref2/assets/textures/Backgrounds.png"
PALETTES_PNG = "/tmp/ark_ref2/assets/textures/Palettes.png"
OUT_DIR = os.path.join(SCRIPT_DIR, "sprite_previews", "arkanoid_pr32")
BG_HEADER_PATH = os.path.join(SCRIPT_DIR, "..", "src", "arkanoid_pr32_bg.h")
PADDLE_HEADER_PATH = os.path.join(SCRIPT_DIR, "..", "src", "arkanoid_pr32_paddle.h")
os.makedirs(OUT_DIR, exist_ok=True)


# Same real-panel R/B swap every other sprite generator in this project
# applies (a real hardware quirk, confirmed against live device photos,
# not a software bug) — see feedback_remote_hw_debugging.md.
def to_rgb565(r, g, b):
    return ((b & 0xF8) << 8) | ((g & 0xFC) << 3) | (r >> 3)


def quantize_and_pack(img, max_colors=15):
    """Quantizes `img` to at most max_colors and packs it 4bpp. Returns
    (packed_bytes, row_stride, palette_rgb[16]) with index 0 reserved for
    the (unused here) transparent slot, matching this project's
    established packed-sprite convention."""
    quantized = img.quantize(colors=max_colors, method=Image.MEDIANCUT)
    palette_flat = quantized.getpalette()
    qpx = quantized.load()
    num_colors = len(quantized.getcolors())
    assert num_colors <= max_colors, f"{num_colors} colors, need <={max_colors}"

    palette_rgb = [(0, 0, 0)]
    for i in range(num_colors):
        palette_rgb.append((palette_flat[i * 3], palette_flat[i * 3 + 1], palette_flat[i * 3 + 2]))
    while len(palette_rgb) < 16:
        palette_rgb.append((0, 0, 0))

    w, h = img.size
    row_stride = (w * 4 + 7) // 8
    data = bytearray(row_stride * h)
    for y in range(h):
        for x in range(w):
            idx = qpx[x, y] + 1  # +1 to skip the reserved transparent slot 0
            byte_i = y * row_stride + (x >> 1)
            if x & 1:
                data[byte_i] |= (idx & 0x0F) << 4
            else:
                data[byte_i] |= (idx & 0x0F)
    return data, palette_rgb


def write_header(path, guard_comment, sprite_defs, palette_rgb, namespace):
    lines = []
    lines.append(f"// AUTO-GENERATED by tools/make_arkanoid_pr32_bg.py — do not hand-edit.")
    lines.append(f"// {guard_comment}")
    lines.append("#pragma once")
    lines.append("#include <cstdint>")
    lines.append("#include <graphics/Renderer.h>")
    lines.append("")
    lines.append(f"namespace {namespace} {{")
    lines.append("")
    for const_name, data, _w, _h in sprite_defs:
        hex_bytes = ", ".join(f"0x{b:02X}" for b in data)
        lines.append(f"static const uint8_t {const_name}_DATA[] = {{ {hex_bytes} }};")
    lines.append("")
    lines.append("static const uint16_t PALETTE_RGB565[16] = {")
    lines.append("    " + ", ".join(f"0x{to_rgb565(r, g, b):04X}" for (r, g, b) in palette_rgb))
    lines.append("};")
    lines.append("")
    lines.append("static const pixelroot32::graphics::Color PALETTE_COLORS[16] = {")
    lines.append("    " + ", ".join(f"static_cast<pixelroot32::graphics::Color>({i})" for i in range(16)))
    lines.append("};")
    lines.append("")
    for const_name, _data, w, h in sprite_defs:
        lines.append(
            f"static const pixelroot32::graphics::Sprite4bpp {const_name} = "
            f"{{ {const_name}_DATA, PALETTE_COLORS, {w}, {h}, 16 }};"
        )
    lines.append("")
    lines.append(f"}} // namespace {namespace}")
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")


# ============================================================ BACKGROUND
# 5 rounds, each pointed at one of the sheet's own distinct tile
# variants (all 224x241, laid out in a 5-wide top row at y=0) — matched
# by theme to wkeeling/arkanoid's own per-round _get_background_colour():
# round1/5=BLUE, round2=GREEN, round3=BLUE (a second, visually distinct
# blue tile so it doesn't look identical to round1), round4=RED. A 6th,
# unused-by-any-round tile (index 3, gray/red) is exported too for the
# boss encounter's own background.
TILE_W, TILE_H = 224, 241
TARGET_W, TARGET_H = 240, 288  # SCREEN_W x (SCREEN_H - kTopWallY) — the FULL area, walls included
SLICE_H = TARGET_H // 2  # 144 each, comfortably under the uint8_t 255 cap

ROUND_TILES = {
    "ROUND1": 0,
    "ROUND2": 1,
    "ROUND3": 2,
    "ROUND4": 4,
    "ROUND5": 0,
    "BOSS": 3,
}

# Actual measured tile x-offsets in the sheet (NOT perfectly uniform —
# confirmed by scanning for the white gap columns between tiles this
# session: 0, 232, 464, 696, 926).
TILE_X_OFFSETS = [0, 232, 464, 696, 926]

sheet = Image.open(BG_PNG).convert("RGB")
bg_sprite_defs = []
bg_lines_extra = []  # extra per-round PALETTE_RGB565 arrays
for name, tile_index in ROUND_TILES.items():
    tx = TILE_X_OFFSETS[tile_index]
    tile = sheet.crop((tx, 0, tx + TILE_W, TILE_H))
    tile = tile.resize((TARGET_W, TARGET_H), Image.LANCZOS)
    tile.save(os.path.join(OUT_DIR, f"{name.lower()}_bg_resized.png"))

    data, palette = quantize_and_pack(tile, max_colors=15)
    row_stride = (TARGET_W * 4 + 7) // 8
    top_data = data[: row_stride * SLICE_H]
    bottom_data = data[row_stride * SLICE_H:]

    bg_sprite_defs.append((f"{name}_BG_TOP", top_data, TARGET_W, SLICE_H, palette))
    bg_sprite_defs.append((f"{name}_BG_BOTTOM", bottom_data, TARGET_W, TARGET_H - SLICE_H, palette))

# Custom multi-palette header: unlike the single-palette write_header()
# helper, each round's background needs its OWN palette (they're visually
# distinct tiles), while PALETTE_COLORS (just an identity map 0..15) is
# shared by all of them.
lines = []
lines.append("// AUTO-GENERATED by tools/make_arkanoid_pr32_bg.py — do not hand-edit.")
lines.append("// All 5 rounds' backgrounds (+ the boss encounter's) — floor + wall border,")
lines.append("// walls included, each split into two vertical slices for Sprite4bpp's")
lines.append("// uint8_t height limit. Cropped from dawid-wolinski/arkanoid-game's")
lines.append("// assets/textures/Backgrounds.png. Each has its OWN palette (switch via")
lines.append("// setSpriteCustomPalette(arkanoid_pr32_bg::ROUNDn_PALETTE_RGB565) before")
lines.append("// drawing that round's *_BG_TOP/*_BG_BOTTOM sprites).")
lines.append("#pragma once")
lines.append("#include <cstdint>")
lines.append("#include <graphics/Renderer.h>")
lines.append("")
lines.append("namespace arkanoid_pr32_bg {")
lines.append("")
for const_name, data, _w, _h, _pal in bg_sprite_defs:
    hex_bytes = ", ".join(f"0x{b:02X}" for b in data)
    lines.append(f"static const uint8_t {const_name}_DATA[] = {{ {hex_bytes} }};")
lines.append("")
lines.append("static const pixelroot32::graphics::Color PALETTE_COLORS[16] = {")
lines.append("    " + ", ".join(f"static_cast<pixelroot32::graphics::Color>({i})" for i in range(16)))
lines.append("};")
lines.append("")
seen_palettes = set()
for name in ROUND_TILES:
    if name in seen_palettes:
        continue
    seen_palettes.add(name)
    # Find this round's palette (both its TOP/BOTTOM entries share one).
    pal = next(p for (n, _d, _w, _h, p) in bg_sprite_defs if n == f"{name}_BG_TOP")
    lines.append(f"static const uint16_t {name}_PALETTE_RGB565[16] = {{")
    lines.append("    " + ", ".join(f"0x{to_rgb565(r, g, b):04X}" for (r, g, b) in pal))
    lines.append("};")
lines.append("")
for const_name, _data, w, h, _pal in bg_sprite_defs:
    lines.append(
        f"static const pixelroot32::graphics::Sprite4bpp {const_name} = "
        f"{{ {const_name}_DATA, PALETTE_COLORS, {w}, {h}, 16 }};"
    )
lines.append("")
lines.append("} // namespace arkanoid_pr32_bg")
with open(BG_HEADER_PATH, "w") as f:
    f.write("\n".join(lines) + "\n")

# ================================================================ PADDLE
PADDLE_BOX = (208, 34, 252, 41)  # empirically located (see docstring), 44x7 native
PADDLE_TARGET_W, PADDLE_TARGET_H = 37, 10  # per explicit user spec: 2.2x/1.2x a brick tile

palettes_sheet = Image.open(PALETTES_PNG).convert("RGB")
paddle_img = palettes_sheet.crop(PADDLE_BOX)
paddle_img = paddle_img.resize((PADDLE_TARGET_W, PADDLE_TARGET_H), Image.LANCZOS)
paddle_img.save(os.path.join(OUT_DIR, "paddle_resized.png"))

paddle_data, paddle_palette = quantize_and_pack(paddle_img, max_colors=15)
write_header(
    PADDLE_HEADER_PATH,
    "Vaus paddle, packed 4bpp. Cropped from dawid-wolinski/arkanoid-game's "
    "assets/textures/Palettes.png (empirically located — see this script's docstring).",
    [("PADDLE", paddle_data, PADDLE_TARGET_W, PADDLE_TARGET_H)],
    paddle_palette,
    "arkanoid_pr32_paddle",
)

print(f"Backgrounds: {len(ROUND_TILES)} tiles x {TARGET_W}x{TARGET_H} split into "
      f"{SLICE_H} + {TARGET_H - SLICE_H}")
print(f"Paddle: {PADDLE_TARGET_W}x{PADDLE_TARGET_H}, {len(paddle_data)} bytes packed")
