"""
Exports Galaga's sprites as packed 4bpp indexed bitmaps for PixelRoot32,
cropped directly from the reference project's own small, faithful pixel
art (TheCoderRaman/CppGalaga, cloned to /tmp/galaga_ref/Galaga/res/graphic —
MIT-style hobby project, sprites are original small pixel art, not
arcade ROM rips). Same crop->pack_4bpp->export pipeline as
tools/make_pacman_pr32_sprites.py (see that script's docstring for the
packed-format rationale) — only the source sheets and crop boxes differ.

Sheet layout (confirmed by direct inspection this session):
  enemy_1.png / enemy_2.png / enemy_3.png / fighter.png / fighter_captured.png
    -> 384x16 = a 24-frame, 16x16-per-frame full-rotation sheet (15-degree
       steps). Boss/guard/minion/fighter/captured-fighter all use this
       same layout. All 24 frames are exported (cheap at 4bpp — see the
       plan file's own budget math), not a reduced subset, since the
       user wants this port genuinely faithful, not simplified.
  enemy_explosion.png -> 160x32 = 5 frames of 32x32.
  fighter_explosion.png -> 128x32 = 4 frames of 32x32.
  enemy_bullet.png / fighter_bullet.png -> 3x8, single frame each.

enemy_beam.png (the boss's tractor beam) is deliberately NOT cropped
here — ported as a simple growing primitive shape in galaga_pr32.cpp
instead of a sprite, since the reference's exact clip/scale-based
extend animation isn't worth the complexity for a first pass. Revisit
if the primitive version doesn't read well on real hardware.
"""
import os
from PIL import Image

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REF_DIR = "/tmp/galaga_ref/Galaga/res/graphic"
OUT_DIR = os.path.join(SCRIPT_DIR, "sprite_previews", "galaga_pr32")
HEADER_PATH = os.path.join(SCRIPT_DIR, "..", "src", "galaga_pr32_sprites.h")
os.makedirs(OUT_DIR, exist_ok=True)

ALPHA_THRESHOLD = 128
FRAME = 16
NUM_ROT_FRAMES = 24

sprites = {}


def save_sprite(name, img):
    sprites[name] = (img.width, img.height, img)
    img.save(f"{OUT_DIR}/{name}.png")


def load(name):
    return Image.open(os.path.join(REF_DIR, name)).convert("RGBA")


# ============================================================ ROTATION SHEETS
for sheet_name, prefix in [
    ("enemy_1.png", "boss"),
    ("enemy_1_hit.png", "boss_hit"),
    ("enemy_2.png", "guard"),
    ("enemy_3.png", "minion"),
    ("fighter.png", "fighter"),
    ("fighter_captured.png", "fighter_captured"),
]:
    sheet = load(sheet_name)
    for f in range(NUM_ROT_FRAMES):
        box = (f * FRAME, 0, f * FRAME + FRAME, FRAME)
        save_sprite(f"{prefix}_{f}", sheet.crop(box))

# ================================================================ EXPLOSIONS
enemy_expl = load("enemy_explosion.png")
for f in range(5):
    box = (f * 32, 0, f * 32 + 32, 32)
    save_sprite(f"enemy_explosion_{f}", enemy_expl.crop(box))

fighter_expl = load("fighter_explosion.png")
for f in range(4):
    box = (f * 32, 0, f * 32 + 32, 32)
    save_sprite(f"fighter_explosion_{f}", fighter_expl.crop(box))

# =================================================================== BULLETS
save_sprite("enemy_bullet", load("enemy_bullet.png"))
save_sprite("fighter_bullet", load("fighter_bullet.png"))

# ============================================================== EXPORT =====
palette_rgb = [(0, 0, 0)]
color_to_index = {(0, 0, 0): 0}


# Same real-panel R/B swap this session already found is needed for
# every custom-sprite-palette scene on this hardware (menu, Pac-Man) —
# a software screenshot of the internal buffer looks correct either way,
# but the physical panel shows chromatic colors with red/blue swapped
# for indexed Sprite4bpp draws specifically. Applying it here
# preemptively rather than waiting to rediscover the same bug again;
# tools/rig.py's screenshot(..., swap_rb=True) compensates when viewing.
def to_rgb565(r, g, b):
    return ((b & 0xF8) << 8) | ((g & 0xFC) << 3) | (r >> 3)


def palette_index_for(rgb):
    if rgb not in color_to_index:
        if len(palette_rgb) >= 16:
            raise ValueError(f"Palette overflow: {rgb} would be the 17th color")
        color_to_index[rgb] = len(palette_rgb)
        palette_rgb.append(rgb)
    return color_to_index[rgb]


def pack_4bpp(img):
    w, h = img.size
    px = img.load()
    row_stride = (w * 4 + 7) // 8
    data = bytearray(row_stride * h)
    for y in range(h):
        for x in range(w):
            r, g, b, a = px[x, y]
            idx = 0 if a < ALPHA_THRESHOLD else palette_index_for((r, g, b))
            byte_i = y * row_stride + (x >> 1)
            if x & 1:
                data[byte_i] |= (idx & 0x0F) << 4
            else:
                data[byte_i] |= (idx & 0x0F)
    return data, row_stride


header_lines = []
header_lines.append("// AUTO-GENERATED by tools/make_galaga_pr32_sprites.py — do not hand-edit.")
header_lines.append("// Galaga sprites, packed 4bpp indexed for PixelRoot32.")
header_lines.append("// Cropped from TheCoderRaman/CppGalaga's own pixel art (see that repo).")
header_lines.append("#pragma once")
header_lines.append("#include <cstdint>")
header_lines.append("#include <graphics/Renderer.h>")
header_lines.append("")
header_lines.append("namespace galaga_pr32_sprites {")
header_lines.append("")

sprite_blocks = []
for name, (w, h, img) in sprites.items():
    data, row_stride = pack_4bpp(img)
    const_name = f"GX_{name.upper()}"
    hex_bytes = ", ".join(f"0x{b:02X}" for b in data)
    header_lines.append(f"static const uint8_t {const_name}_DATA[] = {{ {hex_bytes} }};")
    sprite_blocks.append((const_name, w, h))
header_lines.append("")

while len(palette_rgb) < 16:
    palette_rgb.append((0, 0, 0))

header_lines.append("static const uint16_t PALETTE_RGB565[16] = {")
header_lines.append("    " + ", ".join(f"0x{to_rgb565(r, g, b):04X}" for (r, g, b) in palette_rgb))
header_lines.append("};")
header_lines.append("")
header_lines.append("static const pixelroot32::graphics::Color PALETTE_COLORS[16] = {")
header_lines.append("    " + ", ".join(f"static_cast<pixelroot32::graphics::Color>({i})" for i in range(16)))
header_lines.append("};")
header_lines.append("")

for const_name, w, h in sprite_blocks:
    header_lines.append(
        f"static const pixelroot32::graphics::Sprite4bpp {const_name} = "
        f"{{ {const_name}_DATA, PALETTE_COLORS, {w}, {h}, 16 }};"
    )
header_lines.append("")

# Per-rotation-sheet arrays for easy frame indexing in code (frame_ 0..23).
for prefix in ["boss", "boss_hit", "guard", "minion", "fighter", "fighter_captured"]:
    names = ", ".join(f"&GX_{prefix.upper()}_{f}" for f in range(NUM_ROT_FRAMES))
    header_lines.append(
        f"static const pixelroot32::graphics::Sprite4bpp* const {prefix.upper()}_FRAMES[{NUM_ROT_FRAMES}] = {{ {names} }};"
    )
header_lines.append("")
names = ", ".join(f"&GX_ENEMY_EXPLOSION_{f}" for f in range(5))
header_lines.append(f"static const pixelroot32::graphics::Sprite4bpp* const ENEMY_EXPLOSION_FRAMES[5] = {{ {names} }};")
names = ", ".join(f"&GX_FIGHTER_EXPLOSION_{f}" for f in range(4))
header_lines.append(f"static const pixelroot32::graphics::Sprite4bpp* const FIGHTER_EXPLOSION_FRAMES[4] = {{ {names} }};")
header_lines.append("")
header_lines.append("} // namespace galaga_pr32_sprites")

with open(HEADER_PATH, "w") as f:
    f.write("\n".join(header_lines) + "\n")

print("Generated", len(sprites), "sprites,", len(color_to_index), "colors used (of 15 available)")
