"""
Authors pixel-art block-cell bitmaps for Tetris (hand-drawn via PIL, not a
generative model), converts each to RGB565, and emits a C header. See
tools/make_rtype_sprites.py for the base technique (4x supersampled draw ->
box-filter downscale -> RGB565, background pre-baked so a plain
tft->drawRGBBitmap() blit reads as transparent).

Researched reference (WebSearch, see conversation): the actual 1989 NES
Tetris cartridge did NOT use a fixed color-per-tetromino-shape scheme (it
cycled a 3-color palette every 10 levels instead) - the "I=cyan, O=yellow,
T=purple, S=green, Z=red, J=blue, L=orange" scheme most people picture
today comes from the later Tetris Guideline (2001+). Since the Guideline
colors are what's actually recognized as "the Tetris colors" now (and this
project's PIECE_COLORS already used almost exactly this set), we keep
that palette and combine it with NES-style beveled block-cell rendering
(solid fill + a lighter inset highlight square, giving a small faux-3D
"gem/button" facet) for the authentic retro texture.

Two sizes per color: the main board/falling-piece cell (14x14, matches
CELL in tetris.cpp) and the smaller "next piece" preview cell (11x11,
matches PREV_CELL).
"""
import os
from PIL import Image, ImageDraw

SCALE = 4
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
OUT_DIR = os.path.join(SCRIPT_DIR, "sprite_previews", "tetris")
HEADER_PATH = os.path.join(SCRIPT_DIR, "..", "src", "tetris_sprites.h")
os.makedirs(OUT_DIR, exist_ok=True)

BG = (6, 8, 22)  # matches palette.cpp's BG

def new_canvas(w, h):
    return Image.new("RGBA", (w * SCALE, h * SCALE), (0, 0, 0, 0))

def down(img, w, h):
    return img.resize((w, h), Image.BOX)

def lighten(c, amt):
    return tuple(min(255, v + amt) for v in c)

def darken(c, amt):
    return tuple(max(0, v - amt) for v in c)

sprites = {}

def save_sprite(name, w, h, img):
    sprites[name] = (w, h, img)
    img.save(f"{OUT_DIR}/{name}.png")

# Guideline colors, matching this project's existing PIECE_COLORS order.
PIECES = {
    "i": (60, 220, 255),
    "o": (255, 225, 60),
    "t": (200, 90, 230),
    "s": (100, 220, 100),
    "z": (255, 70, 90),
    "j": (70, 130, 255),
    "l": (255, 150, 50),
}

def make_cell(name, base, size):
    W = H = size
    c = new_canvas(W, H)
    d = ImageDraw.Draw(c)
    S = SCALE
    # Dark outer border (cell separation, like the NES grid look).
    d.rectangle([0, 0, W*S, H*S], fill=darken(base, 60) + (255,))
    # Solid fill.
    d.rectangle([S, S, (W-1)*S, (H-1)*S], fill=base + (255,))
    # NES-style beveled inset: bright top/left edge, dark bottom/right edge.
    inset = max(1.5, W * 0.14)
    d.rectangle([S, S, (W-1)*S, (S + inset)], fill=lighten(base, 70) + (255,))
    d.rectangle([S, S, (S + inset), (H-1)*S], fill=lighten(base, 55) + (255,))
    d.rectangle([S, (H-1)*S - inset, (W-1)*S, (H-1)*S], fill=darken(base, 55) + (255,))
    d.rectangle([(W-1)*S - inset, S, (W-1)*S, (H-1)*S], fill=darken(base, 55) + (255,))
    # Small lighter "gem" facet in the center-upper area for extra shine.
    gx0, gy0 = (W*0.28)*S, (H*0.24)*S
    gx1, gy1 = (W*0.68)*S, (H*0.5)*S
    d.rectangle([gx0, gy0, gx1, gy1], fill=lighten(base, 35) + (255,))
    img = down(c, W, H)
    save_sprite(name, W, H, img)

for name, base in PIECES.items():
    make_cell(f"cell_{name}", base, 14)
    make_cell(f"prevcell_{name}", base, 11)

# ============================================================= EXPORT ======
def to_rgb565(r, g, b):
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)

header_lines = []
header_lines.append("// AUTO-GENERATED by tools/make_tetris_sprites.py — do not hand-edit.")
header_lines.append("// Hand-authored pixel art (PIL script), converted to RGB565, embedded in")
header_lines.append("// flash. \"Empty\" background pixels are pre-baked to the shared BG color")
header_lines.append("// so a plain tft->drawRGBBitmap() blit reads as a transparent sprite.")
header_lines.append("#pragma once")
header_lines.append("#include <Arduino.h>")
header_lines.append("")

for name, (w, h, img) in sprites.items():
    rgba = img.convert("RGBA")
    px_data = rgba.load()
    values = []
    for y in range(h):
        for x in range(w):
            r, g, b, a = px_data[x, y]
            if a < 128:
                r, g, b = BG
            elif a < 255:
                r = (r * a + BG[0] * (255 - a)) // 255
                g = (g * a + BG[1] * (255 - a)) // 255
                b = (b * a + BG[2] * (255 - a)) // 255
            values.append(to_rgb565(r, g, b))
    const_name = f"TE_SPR_{name.upper()}"
    header_lines.append(f"const int {const_name}_W = {w};")
    header_lines.append(f"const int {const_name}_H = {h};")
    header_lines.append(f"const uint16_t {const_name}[{w*h}] PROGMEM = {{")
    for row in range(0, len(values), 12):
        chunk = values[row:row+12]
        header_lines.append("  " + ", ".join(f"0x{v:04X}" for v in chunk) + ",")
    header_lines.append("};")
    header_lines.append("")

with open(HEADER_PATH, "w") as f:
    f.write("\n".join(header_lines))

print("Generated", len(sprites), "sprites")
for name, (w, h, _) in sprites.items():
    print(f"  {name}: {w}x{h}")
