"""
Authors pixel-art bubble sprite bitmaps for Bust-a-Move (hand-drawn via
PIL, not a generative model), converts each to RGB565, and emits a C
header. See tools/make_rtype_sprites.py for the base technique (4x
supersampled draw -> box-filter downscale -> RGB565, background pre-baked
so a plain tft->drawRGBBitmap() blit reads as transparent).

Researched reference (WebSearch, see conversation): the original 1994
Taito arcade bubbles are solid-colored glossy spheres — a flat/solid base
hue, a small circular specular highlight toward the upper-left (the
classic glass-marble look), and a thin dark outline ring — with NO
printed numbers or symbols; color alone distinguishes them. This project
already used almost exactly that recipe as live vector draws
(fillCircle+highlight+outline); this is a straight bitmap-ification of
the same look, not a redesign, plus a bit more shading depth than the
vector version could cheaply do.

Two sizes: the main grid/flying/loaded bubble (matches R-1 radius, 17px
diameter) and the small "next bubble" preview (matches radius 6, 13px
diameter).
"""
import os
from PIL import Image, ImageDraw

SCALE = 4
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
OUT_DIR = os.path.join(SCRIPT_DIR, "sprite_previews", "bustamove")
HEADER_PATH = os.path.join(SCRIPT_DIR, "..", "src", "bustamove_sprites.h")
os.makedirs(OUT_DIR, exist_ok=True)

BG = (6, 8, 22)  # matches palette.cpp's BG

def new_canvas(w, h):
    return Image.new("RGBA", (w * SCALE, h * SCALE), (0, 0, 0, 0))

def down(img, w, h):
    return img.resize((w, h), Image.BOX)

def lighten(c, amt):
    return tuple(min(255, v + amt) for v in c)

def darken(c, amt):
    return tuple(max(0, v - amt) for v in c)

sprites = {}

def save_sprite(name, w, h, img):
    sprites[name] = (w, h, img)
    img.save(f"{OUT_DIR}/{name}.png")

BUBBLE_COLORS = {
    "red":    (230, 60, 70),
    "blue":   (70, 140, 255),
    "green":  (90, 220, 110),
    "yellow": (250, 210, 60),
    "purple": (200, 90, 230),
    "cyan":   (60, 220, 220),
}

def make_bubble(name, base, size):
    W = H = size
    c = new_canvas(W, H)
    d = ImageDraw.Draw(c)
    S = SCALE
    r = (W / 2) * S
    cx = cy = W / 2 * S
    # Dark outline ring.
    d.ellipse([0, 0, W*S, H*S], fill=darken(base, 55) + (255,))
    # Solid base fill, slightly inset from the outline.
    inset = S * 0.6
    d.ellipse([inset, inset, W*S - inset, H*S - inset], fill=base + (255,))
    # Soft lower-right shading for volume.
    d.ellipse([cx - r*0.15, cy - r*0.15, cx + r*1.05, cy + r*1.05], fill=darken(base, 30) + (200,))
    d.ellipse([inset, inset, W*S - inset, H*S - inset], fill=None, outline=None)
    # Redraw base on top of the shading ellipse but offset up-left so the
    # shading only peeks out at the bottom-right rim.
    d.ellipse([inset, inset, W*S - inset - r*0.12, H*S - inset - r*0.12], fill=base + (255,))
    # Specular highlight, upper-left, classic glass-marble look.
    hl_cx, hl_cy = cx - r*0.42, cy - r*0.42
    hl_r = r * 0.32
    d.ellipse([hl_cx - hl_r, hl_cy - hl_r, hl_cx + hl_r, hl_cy + hl_r], fill=lighten(base, 90) + (230,))
    d.ellipse([hl_cx - hl_r*0.4, hl_cy - hl_r*0.5, hl_cx + hl_r*0.4, hl_cy + hl_r*0.2],
              fill=(255, 255, 255, 255))
    img = down(c, W, H)
    save_sprite(name, W, H, img)

for name, base in BUBBLE_COLORS.items():
    make_bubble(f"bubble_{name}", base, 17)
    make_bubble(f"bubblesmall_{name}", base, 13)

# ============================================================= EXPORT ======
def to_rgb565(r, g, b):
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)

header_lines = []
header_lines.append("// AUTO-GENERATED by tools/make_bustamove_sprites.py — do not hand-edit.")
header_lines.append("// Hand-authored pixel art (PIL script), converted to RGB565, embedded in")
header_lines.append("// flash. \"Empty\" background pixels are pre-baked to the shared BG color")
header_lines.append("// so a plain tft->drawRGBBitmap() blit reads as a transparent sprite.")
header_lines.append("#pragma once")
header_lines.append("#include <Arduino.h>")
header_lines.append("")

for name, (w, h, img) in sprites.items():
    rgba = img.convert("RGBA")
    px_data = rgba.load()
    values = []
    for y in range(h):
        for x in range(w):
            r, g, b, a = px_data[x, y]
            if a < 128:
                r, g, b = BG
            elif a < 255:
                r = (r * a + BG[0] * (255 - a)) // 255
                g = (g * a + BG[1] * (255 - a)) // 255
                b = (b * a + BG[2] * (255 - a)) // 255
            values.append(to_rgb565(r, g, b))
    const_name = f"BM_SPR_{name.upper()}"
    header_lines.append(f"const int {const_name}_W = {w};")
    header_lines.append(f"const int {const_name}_H = {h};")
    header_lines.append(f"const uint16_t {const_name}[{w*h}] PROGMEM = {{")
    for row in range(0, len(values), 12):
        chunk = values[row:row+12]
        header_lines.append("  " + ", ".join(f"0x{v:04X}" for v in chunk) + ",")
    header_lines.append("};")
    header_lines.append("")

with open(HEADER_PATH, "w") as f:
    f.write("\n".join(header_lines))

print("Generated", len(sprites), "sprites")
for name, (w, h, _) in sprites.items():
    print(f"  {name}: {w}x{h}")
