"""
Draws an ORIGINAL boss creature for Arkanoid's round-5-clear encounter,
entirely from scratch with PIL primitives — not cropped or traced from
any reference project (the second reference's own Boss.png is a
detailed, specific totem-head character design, a different category
from the generic floor/wall textures this project's other assets came
from, so it wasn't used as source art — see this session's conversation
for that call). Boss *mechanics* (HP, hit-flash at low HP, death
sequence) are still ported faithfully from that reference's boss.cpp,
since that's just code/logic, not character art.

Design: a floating mechanical "core" — a hexagonal plated shell around a
pulsing eye-core, magenta/purple plating with a cyan core that shifts
red the more damaged it is. 3 frames: idle pulse (2 frames) + a
hit-flash (white) frame.
"""
import os
from PIL import Image, ImageDraw

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
OUT_DIR = os.path.join(SCRIPT_DIR, "sprite_previews", "arkanoid_pr32")
HEADER_PATH = os.path.join(SCRIPT_DIR, "..", "src", "arkanoid_pr32_boss.h")
os.makedirs(OUT_DIR, exist_ok=True)

W, H = 48, 40


def draw_boss(core_color, flash=False):
    img = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    cx, cy = W / 2, H / 2

    shell = (255, 255, 255, 255) if flash else (150, 60, 200, 255)
    shell_dark = (255, 255, 255, 255) if flash else (100, 30, 150, 255)
    plate = (255, 255, 255, 255) if flash else (190, 110, 230, 255)

    # Hexagonal outer shell.
    hexpts = [
        (cx, cy - 19), (cx + 20, cy - 9), (cx + 20, cy + 9),
        (cx, cy + 19), (cx - 20, cy + 9), (cx - 20, cy - 9),
    ]
    d.polygon(hexpts, fill=shell, outline=shell_dark)

    # Inner plates (segments), only when not flashing (keep flash a
    # solid white silhouette so the hit-flash reads clearly).
    if not flash:
        d.polygon([(cx, cy - 19), (cx + 20, cy - 9), (cx, cy - 2), (cx - 20, cy - 9)], fill=plate)
        d.polygon([(cx, cy + 19), (cx + 20, cy + 9), (cx, cy + 2), (cx - 20, cy + 9)], fill=shell_dark)

    # Small corner rivets.
    for rx, ry in [(cx - 20, cy - 9), (cx + 20, cy - 9), (cx - 20, cy + 9), (cx + 20, cy + 9)]:
        d.ellipse([rx - 2, ry - 2, rx + 2, ry + 2], fill=(60, 60, 70, 255) if not flash else (255, 255, 255, 255))

    # Pulsing eye-core.
    core_c = (255, 255, 255, 255) if flash else core_color
    d.ellipse([cx - 8, cy - 8, cx + 8, cy + 8], fill=(20, 10, 30, 255) if not flash else (255, 255, 255, 255))
    d.ellipse([cx - 6, cy - 6, cx + 6, cy + 6], fill=core_c)
    d.ellipse([cx - 3, cy - 3, cx + 3, cy + 3], fill=(255, 255, 255, 255))

    return img


frame_idle_a = draw_boss((60, 220, 230, 255))   # cyan core, frame A
frame_idle_b = draw_boss((100, 240, 245, 255))  # cyan core, frame B (slightly brighter pulse)
frame_hit = draw_boss(None, flash=True)         # white hit-flash
frame_low_hp = draw_boss((230, 60, 60, 255))    # red core, low-HP state

frames = [frame_idle_a, frame_idle_b, frame_hit, frame_low_hp]
names = ["BOSS_IDLE_A", "BOSS_IDLE_B", "BOSS_HIT", "BOSS_LOW_HP"]
for n, f in zip(names, frames):
    f.save(os.path.join(OUT_DIR, f"{n.lower()}.png"))


def to_rgb565(r, g, b):
    return ((b & 0xF8) << 8) | ((g & 0xFC) << 3) | (r >> 3)


ALPHA_THRESHOLD = 128
palette_rgb = [(0, 0, 0)]
color_to_index = {(0, 0, 0): 0}


def palette_index_for(rgb):
    if rgb not in color_to_index:
        if len(palette_rgb) >= 16:
            raise ValueError(f"Palette overflow: {rgb} would be the 17th color")
        color_to_index[rgb] = len(palette_rgb)
        palette_rgb.append(rgb)
    return color_to_index[rgb]


def pack_4bpp(img):
    w, h = img.size
    px = img.load()
    row_stride = (w * 4 + 7) // 8
    data = bytearray(row_stride * h)
    for y in range(h):
        for x in range(w):
            r, g, b, a = px[x, y]
            idx = 0 if a < ALPHA_THRESHOLD else palette_index_for((r, g, b))
            byte_i = y * row_stride + (x >> 1)
            if x & 1:
                data[byte_i] |= (idx & 0x0F) << 4
            else:
                data[byte_i] |= (idx & 0x0F)
    return data


frame_data = [pack_4bpp(f) for f in frames]
while len(palette_rgb) < 16:
    palette_rgb.append((0, 0, 0))

header_lines = []
header_lines.append("// AUTO-GENERATED by tools/make_arkanoid_pr32_boss.py — do not hand-edit.")
header_lines.append("// An ORIGINAL boss creature design (not from any reference) — see this")
header_lines.append("// script's docstring for why the reference's own Boss.png wasn't used.")
header_lines.append("#pragma once")
header_lines.append("#include <cstdint>")
header_lines.append("#include <graphics/Renderer.h>")
header_lines.append("")
header_lines.append("namespace arkanoid_pr32_boss {")
header_lines.append("")
for i, data in enumerate(frame_data):
    hex_bytes = ", ".join(f"0x{b:02X}" for b in data)
    header_lines.append(f"static const uint8_t {names[i]}_DATA[] = {{ {hex_bytes} }};")
header_lines.append("")
header_lines.append("static const uint16_t PALETTE_RGB565[16] = {")
header_lines.append("    " + ", ".join(f"0x{to_rgb565(r, g, b):04X}" for (r, g, b) in palette_rgb))
header_lines.append("};")
header_lines.append("")
header_lines.append("static const pixelroot32::graphics::Color PALETTE_COLORS[16] = {")
header_lines.append("    " + ", ".join(f"static_cast<pixelroot32::graphics::Color>({i})" for i in range(16)))
header_lines.append("};")
header_lines.append("")
for i, n in enumerate(names):
    header_lines.append(
        f"static const pixelroot32::graphics::Sprite4bpp {n} = "
        f"{{ {n}_DATA, PALETTE_COLORS, {W}, {H}, 16 }};"
    )
header_lines.append("")
header_lines.append("} // namespace arkanoid_pr32_boss")

with open(HEADER_PATH, "w") as f:
    f.write("\n".join(header_lines) + "\n")

print(f"Generated {W}x{H} boss, {len(frames)} frames, {len(color_to_index)} colors used (of 15 available)")
